services:
  - type: web
    name: alankarini-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
